# Generated by Django 6.0.6 on 2026-07-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calendar_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_format',
            field=models.CharField(choices=[('de_numeric', '31.12.2026'), ('de_long', '31. Dezember 2026'), ('iso', '2026-12-31'), ('us_numeric', '12/31/2026')], default='de_numeric', max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_format',
            field=models.CharField(choices=[('24h', '24-Stunden'), ('12h', '12-Stunden')], default='24h', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone_name',
            field=models.CharField(choices=[('Europe/Berlin', 'Europe/Berlin'), ('Europe/Amsterdam', 'Europe/Amsterdam'), ('Europe/London', 'Europe/London'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Rome', 'Europe/Rome'), ('Europe/Madrid', 'Europe/Madrid'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York'), ('America/Los_Angeles', 'America/Los_Angeles'), ('Asia/Tokyo', 'Asia/Tokyo')], default='Europe/Berlin', max_length=64),
        ),
    ]
