# Generated by Django 5.2.15 on 2026-07-03 08:18
# Adjusted to be idempotent for local SQLite databases where the chat tables
# may already exist from a partially applied migration attempt.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CREATE_CHAT_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS "app_conversation" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" varchar(140) NOT NULL,
    "is_group" bool NOT NULL,
    "created_at" datetime NOT NULL,
    "updated_at" datetime NOT NULL,
    "created_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS "app_conversationmember" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "is_archived" bool NOT NULL,
    "last_read_at" datetime NULL,
    "joined_at" datetime NOT NULL,
    "conversation_id" bigint NOT NULL REFERENCES "app_conversation" ("id") DEFERRABLE INITIALLY DEFERRED,
    "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS "app_chatmessage" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "body" text NOT NULL,
    "created_at" datetime NOT NULL,
    "edited_at" datetime NULL,
    "sender_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "conversation_id" bigint NOT NULL REFERENCES "app_conversation" ("id") DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS "app_conversation_created_by_id_a2304738"
    ON "app_conversation" ("created_by_id");
CREATE INDEX IF NOT EXISTS "app_conversationmember_conversation_id_853531f6"
    ON "app_conversationmember" ("conversation_id");
CREATE INDEX IF NOT EXISTS "app_conversationmember_user_id_df749e4c"
    ON "app_conversationmember" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "unique_conversation_member"
    ON "app_conversationmember" ("conversation_id", "user_id");
CREATE INDEX IF NOT EXISTS "app_chatmessage_sender_id_c2ea3a84"
    ON "app_chatmessage" ("sender_id");
CREATE INDEX IF NOT EXISTS "app_chatmessage_conversation_id_5bd2dd0f"
    ON "app_chatmessage" ("conversation_id");
CREATE INDEX IF NOT EXISTS "app_chatmes_convers_fb6bdc_idx"
    ON "app_chatmessage" ("conversation_id", "created_at");
CREATE INDEX IF NOT EXISTS "app_chatmes_sender__a7a0ce_idx"
    ON "app_chatmessage" ("sender_id", "created_at");
"""

DROP_CHAT_TABLES_SQL = """
DROP TABLE IF EXISTS "app_chatmessage";
DROP TABLE IF EXISTS "app_conversationmember";
DROP TABLE IF EXISTS "app_conversation";
"""


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_date_format_profile_time_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(CREATE_CHAT_TABLES_SQL, reverse_sql=DROP_CHAT_TABLES_SQL),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Conversation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(blank=True, max_length=140)),
                        ('is_group', models.BooleanField(default=False)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['-updated_at', '-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ConversationMember',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_archived', models.BooleanField(default=False)),
                        ('last_read_at', models.DateTimeField(blank=True, null=True)),
                        ('joined_at', models.DateTimeField(auto_now_add=True)),
                        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_rows', to='app.conversation')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_memberships', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'ordering': ['joined_at'],
                    },
                ),
                migrations.AddField(
                    model_name='conversation',
                    name='participants',
                    field=models.ManyToManyField(related_name='conversations', through='app.ConversationMember', to=settings.AUTH_USER_MODEL),
                ),
                migrations.CreateModel(
                    name='ChatMessage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('body', models.TextField(max_length=4000)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('edited_at', models.DateTimeField(blank=True, null=True)),
                        ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
                        ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.conversation')),
                    ],
                    options={
                        'ordering': ['created_at', 'id'],
                        'indexes': [models.Index(fields=['conversation', 'created_at'], name='app_chatmes_convers_fb6bdc_idx'), models.Index(fields=['sender', 'created_at'], name='app_chatmes_sender__a7a0ce_idx')],
                    },
                ),
                migrations.AddConstraint(
                    model_name='conversationmember',
                    constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_member'),
                ),
            ],
        ),
    ]
