# Generated by Django 6.0.6 on 2026-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_chatmessagereaction_chatmessage_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
