# Generated by Django 5.2.9 on 2026-07-04 13:15

import app.services.image_uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_conversationmember_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profiles/', validators=[app.services.image_uploads.validate_profile_image_file]),
        ),
    ]
