# Generated by Django 5.2.9 on 2026-07-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarreminder',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='analytics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_desktop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='usage_data_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='weather_default_city',
            field=models.CharField(blank=True, default='Buende,de', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='weekly_summary',
            field=models.BooleanField(default=False),
        ),
    ]
