# Generated by Django 5.2.9 on 2026-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_calendarreminder_due_at_profile_analytics_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weather_default_city',
            field=models.CharField(blank=True, default='Bünde,de', max_length=120),
        ),
    ]
