# Generated by Django 5.2.9 on 2026-08-04 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_profile_weather_default_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='tone',
        ),
        migrations.AddField(
            model_name='calendarsource',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Gruen'), ('red', 'Rot'), ('sand', 'Sand'), ('violet', 'Violett')], default='blue', max_length=12),
        ),
        migrations.AddField(
            model_name='calendarsource',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calendarsource',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='calendarsource',
            constraint=models.UniqueConstraint(fields=('user', 'ical_url'), name='unique_calendar_source_url_per_user'),
        ),
    ]
