# Generated by Django 5.2.9 on 2026-08-05 11:47

import app.services.note_content
import app.services.note_files
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_systemsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='note_shortcuts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notes_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unbenannte Notiz', max_length=200)),
                ('document', models.JSONField(default=app.services.note_content.empty_note_document)),
                ('plain_text', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_notes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(max_length=500, storage=app.services.note_files.PrivateNoteStorage(), upload_to=app.services.note_files.note_upload_to)),
                ('kind', models.CharField(choices=[('image', 'Bild'), ('file', 'Datei')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=160)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.note')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['normalized_name'],
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='app.notetag'),
        ),
        migrations.CreateModel(
            name='NoteUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='app.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_revision', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('document', models.JSONField()),
                ('tags', models.JSONField(default=list)),
                ('reason', models.CharField(choices=[('autosave', 'Automatisch'), ('restore', 'Vor Wiederherstellung'), ('conflict', 'Vor Überschreiben')], default='autosave', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_versions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app.note')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reader', 'Leser'), ('editor', 'Bearbeiter')], default='reader', max_length=10)),
                ('first_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='app.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('note', 'user'), name='unique_note_share_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='notetag',
            constraint=models.UniqueConstraint(fields=('owner', 'normalized_name'), name='unique_note_tag_per_owner'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'deleted_at', 'updated_at'], name='app_note_owner_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='noteuserstate',
            constraint=models.UniqueConstraint(fields=('note', 'user'), name='unique_note_state_per_user'),
        ),
        migrations.AddIndex(
            model_name='noteversion',
            index=models.Index(fields=['note', 'created_at'], name='app_notever_note_time_idx'),
        ),
    ]
