# Generated by Django 5.2.9 on 2026-08-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def reset_legacy_notification_consent(apps, schema_editor):
    Profile = apps.get_model('app', 'Profile')
    Profile.objects.update(notify_email=False, notify_desktop=False, weekly_summary=False)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_note_shortcuts_systemsettings_notes_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarreminder',
            name='desktop_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarreminder',
            name='email_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklySummaryDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', '-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='unique_weekly_summary_per_user')],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notify_desktop',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(reset_legacy_notification_consent, migrations.RunPython.noop),
    ]
