# Generated by Django 6.0.6 on 2026-08-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_noteactivitynotification_notecommentthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.CharField(blank=True, choices=[('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich'), ('YEARLY', 'Jährlich')], default='', max_length=10),
        ),
    ]
