# Generated by Django 6.0.6 on 2026-08-21 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_calendarevent_recurrence_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='vacation_planner_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.CharField(choices=[('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Wuerttemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thueringen')], max_length=2)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=160)),
                ('day_value', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('active', models.BooleanField(default=True)),
                ('source', models.CharField(default='holidays', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'name'],
                'constraints': [models.UniqueConstraint(fields=('subdivision', 'date', 'name'), name='unique_official_holiday')],
            },
        ),
        migrations.CreateModel(
            name='VacationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('allowance_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('subdivision', models.CharField(choices=[('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Wuerttemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thueringen')], default='NW', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='HolidayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('day_value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official_holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='app.officialholiday')),
                ('vacation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_overrides', to='app.vacationyear')),
            ],
            options={
                'ordering': ['official_holiday__date', 'official_holiday__name'],
            },
        ),
        migrations.CreateModel(
            name='CustomHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=160)),
                ('day_value', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacation_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_holidays', to='app.vacationyear')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VacationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'name', 'id'],
                'indexes': [models.Index(fields=['user', 'start_date', 'end_date'], name='app_vacperiod_user_range_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vacationyear',
            constraint=models.UniqueConstraint(fields=('user', 'year'), name='unique_vacation_year_per_user'),
        ),
        migrations.AddConstraint(
            model_name='holidayoverride',
            constraint=models.UniqueConstraint(fields=('vacation_year', 'official_holiday'), name='unique_holiday_override'),
        ),
        migrations.AddConstraint(
            model_name='customholiday',
            constraint=models.UniqueConstraint(fields=('vacation_year', 'date', 'name'), name='unique_custom_holiday'),
        ),
    ]
