# Generated by Django 6.0.6 on 2026-08-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_systemsettings_vacation_planner_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationperiod',
            name='name',
            field=models.CharField(choices=[('tarifurlaub', 'Tarifurlaub'), ('sonderurlaub', 'Sonderurlaub'), ('ueberstundenabbau', 'Ueberstundenabbau')], default='tarifurlaub', max_length=160),
        ),
    ]
