# Generated by Django 6.0.6 on 2026-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_vacationperiod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialholiday',
            name='subdivision',
            field=models.CharField(choices=[('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thüringen')], max_length=2),
        ),
        migrations.AlterField(
            model_name='vacationperiod',
            name='name',
            field=models.CharField(choices=[('tarifurlaub', 'Tarifurlaub'), ('sonderurlaub', 'Sonderurlaub'), ('ueberstundenabbau', 'Überstundenabbau')], default='tarifurlaub', max_length=160),
        ),
        migrations.AlterField(
            model_name='vacationyear',
            name='subdivision',
            field=models.CharField(choices=[('BB', 'Brandenburg'), ('BE', 'Berlin'), ('BW', 'Baden-Württemberg'), ('BY', 'Bayern'), ('HB', 'Bremen'), ('HE', 'Hessen'), ('HH', 'Hamburg'), ('MV', 'Mecklenburg-Vorpommern'), ('NI', 'Niedersachsen'), ('NW', 'Nordrhein-Westfalen'), ('RP', 'Rheinland-Pfalz'), ('SH', 'Schleswig-Holstein'), ('SL', 'Saarland'), ('SN', 'Sachsen'), ('ST', 'Sachsen-Anhalt'), ('TH', 'Thüringen')], default='NW', max_length=2),
        ),
    ]
