# Generated by Django 6.0.6 on 2026-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_calendarsource_sync_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='desktop_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='email_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='note_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
