# Generated by Django 6.0.6 on 2026-08-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_weatherlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='app.note')),
                ('target_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='app.note')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_note', 'target_note'), name='unique_note_link')],
            },
        ),
    ]
