# Generated by Django 5.2.9 on 2026-08-25

from django.db import migrations, models


def populate_note_tree_positions(apps, schema_editor):
    NoteFolder = apps.get_model("app", "NoteFolder")
    NoteUserState = apps.get_model("app", "NoteUserState")
    user_ids = set(NoteFolder.objects.values_list("owner_id", flat=True))
    user_ids.update(NoteUserState.objects.values_list("user_id", flat=True))

    for user_id in user_ids:
        folder_ids = list(NoteFolder.objects.filter(owner_id=user_id).values_list("id", flat=True))
        for container_id in [None, *folder_ids]:
            states = list(
                NoteUserState.objects.filter(user_id=user_id, folder_id=container_id)
                .select_related("note")
                .order_by("-is_pinned", "-note__updated_at", "-note_id")
            )
            folders = list(
                NoteFolder.objects.filter(owner_id=user_id, parent_id=container_id).order_by("name", "id")
            )
            for index, item in enumerate([*states, *folders], start=1):
                item.position = index * 1000
            if states:
                NoteUserState.objects.bulk_update(states, ["position"])
            if folders:
                NoteFolder.objects.bulk_update(folders, ["position"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_notefolder_noteuserstate_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="notefolder",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="noteuserstate",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_note_tree_positions, migrations.RunPython.noop),
    ]
