# Generated by Django 6.0.6 on 2026-08-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_notetemplate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notetag',
            name='unique_note_tag_per_owner',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='note',
            name='desktop_notified_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='due_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='email_notified_at',
        ),
        migrations.RemoveField(
            model_name='noteversion',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='note_reminders_enabled',
        ),
        migrations.DeleteModel(
            name='NoteTag',
        ),
    ]
