# Generated by Django 6.0.8 on 2026-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_note_tags_and_due_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsource',
            name='color',
            field=models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('red', 'Rot'), ('sand', 'Sand'), ('violet', 'Violett')], default='blue', max_length=12),
        ),
    ]
