# Generated by Codex on 2026-08-26

from django.db import migrations, models

import app.services.dashboard


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_remove_note_tags_and_due_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dashboard_layout",
            field=models.JSONField(blank=True, default=app.services.dashboard.default_dashboard_layout),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="dashboard_customization_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
