# Generated by Django 6.0.8 on 2026-08-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuserstate',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Keine'), ('blue', 'Blau'), ('green', 'Grün'), ('red', 'Rot'), ('sand', 'Sand'), ('violet', 'Violett')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='noteuserstate',
            name='icon',
            field=models.CharField(blank=True, choices=[('', 'Kein Icon'), ('star', 'Stern'), ('flag', 'Flagge'), ('lightbulb', 'Idee'), ('bookmark', 'Lesezeichen'), ('rocket', 'Rakete'), ('heart', 'Herz'), ('circle-exclamation', 'Achtung'), ('circle-check', 'Erledigt'), ('book', 'Buch'), ('briefcase', 'Arbeit'), ('house', 'Privat'), ('code', 'Code')], default='', max_length=24),
        ),
    ]
