# Generated by Django 6.0.8 on 2026-08-28 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_note_user_state_color_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('calendar_reminder', 'Kalendererinnerung'), ('task_due', 'Fällige Aufgabe'), ('event_invitation', 'Termineinladung'), ('note_mention', 'Notizerwähnung'), ('note_comment', 'Notizkommentar'), ('note_share', 'Notizfreigabe'), ('weather_alert', 'Wetterwarnung')], max_length=24)),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(blank=True, max_length=500)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('source_key', models.CharField(max_length=180)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='notification_inbox_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'source_key'), name='unique_user_notification_source')],
            },
        ),
    ]
