# Generated by Django 6.0.8 on 2026-08-28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def mark_existing_generic_emails_handled(apps, schema_editor):
    UserNotification = apps.get_model("app", "UserNotification")
    UserNotification.objects.filter(
        kind__in=["note_share", "weather_alert"],
        email_notified_at__isnull=True,
    ).update(email_notified_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_webpushsubscription_webpushdelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="email_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_quiet_end",
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_quiet_hours_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="notification_quiet_start",
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("calendar", "Kalender"),
                            ("tasks", "Aufgaben"),
                            ("notes", "Notizen"),
                            ("weather", "Wetter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inbox_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("web_push_enabled", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id", "category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"),
                        name="unique_notification_preference",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            mark_existing_generic_emails_handled,
            migrations.RunPython.noop,
        ),
    ]
