# Generated by Django 6.0.8 on 2026-08-28 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_notification_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('none', 'Keine'), ('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.CharField(choices=[('none', 'Keine'), ('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich'), ('YEARLY', 'Jährlich')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('red', 'Rot'), ('sand', 'Sand'), ('violet', 'Violett')], default='blue', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='app.tasklabel'),
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('red', 'Rot'), ('sand', 'Sand'), ('violet', 'Violett')], default='blue', max_length=12)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='app.tasklist'),
        ),
        migrations.AddConstraint(
            model_name='tasklabel',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_task_label_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_task_list_name_per_owner'),
        ),
    ]
