# Generated by Django 6.0.8 on 2026-08-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_task_parent_task_priority_task_recurrence_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('none', 'Keine'), ('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence_rule',
            field=models.CharField(blank=True, choices=[('none', 'Keine'), ('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich'), ('YEARLY', 'Jährlich')], default='none', max_length=10),
        ),
    ]
