# Generated by Django 6.0.8 on 2026-09-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_task_priority_alter_task_recurrence_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
