# Generated by Django 6.0.8 on 2026-09-04 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_task_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteViewerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_until', models.DateTimeField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer_presence', to='app.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['note', 'present_until'], name='notepresence_note_until_idx')],
                'constraints': [models.UniqueConstraint(fields=('note', 'user'), name='unique_note_presence_per_user')],
            },
        ),
    ]
