# Generated by Django 6.0.8 on 2026-09-30 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0045_uml_diagram_tools"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "source_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("de", "Deutsch"),
                            ("en", "Englisch"),
                            ("fr", "Französisch"),
                            ("es", "Spanisch"),
                            ("it", "Italienisch"),
                            ("la", "Latein"),
                            ("nl", "Niederländisch"),
                            ("pl", "Polnisch"),
                            ("ru", "Russisch"),
                            ("tr", "Türkisch"),
                            ("", "Andere"),
                        ],
                        default="en",
                        max_length=8,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("de", "Deutsch"),
                            ("en", "Englisch"),
                            ("fr", "Französisch"),
                            ("es", "Spanisch"),
                            ("it", "Italienisch"),
                            ("la", "Latein"),
                            ("nl", "Niederländisch"),
                            ("pl", "Polnisch"),
                            ("ru", "Russisch"),
                            ("tr", "Türkisch"),
                            ("", "Andere"),
                        ],
                        default="de",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VocabularyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("term", models.CharField(max_length=200)),
                ("translation", models.CharField(max_length=200)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("box", models.PositiveSmallIntegerField(default=1)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("wrong_count", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vocabulary_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="app.vocabularylist",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
