from django.contrib.auth.views import LogoutView
from django.urls import path
from django.views.generic import RedirectView

import app.views as view

login_view = view.LunoraLoginView.as_view()

urlpatterns = [
    path("", RedirectView.as_view(url="/home/", permanent=False)),
    path("service-worker.js", view.service_worker, name="service_worker"),
    path("offline/", view.offline, name="offline"),
    path("login/", login_view, name="login"),
    path("accounts/login/", login_view, name="accounts_login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", view.register, name="register"),
    path("password-reset/", view.LunoraPasswordResetView.as_view(), name="password_reset"),
    path("password-reset/done/", view.LunoraPasswordResetDoneView.as_view(), name="password_reset_done"),
    path(
        "reset/<uidb64>/<token>/",
        view.LunoraPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", view.LunoraPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("administration/", view.administration, name="administration"),
    path("home/", view.home, name="home"),
    path("home/dashboard-layout/", view.dashboard_layout_update, name="dashboard_layout_update"),
    path("search/", view.global_search, name="global_search"),
    path("settings/", view.settings, name="settings"),
    path("weather/", view.weather, name="weather"),
    path("weather/point/", view.weather_point, name="weather_point"),
    path("weather/suggest/", view.weather_suggestions, name="weather_suggestions"),
    path(
        "weather/map/<str:layer>/<int:z>/<int:x>/<int:y>.png",
        view.weather_map_tile,
        name="weather_map_tile",
    ),
    path("calendar/", view.calendar, name="calendar"),
    path("tasks/", view.tasks, name="tasks"),
    path("vacation-planner/", view.vacation_planner, name="vacation_planner"),
    path("vacation-planner/year/", view.vacation_year_save, name="vacation_year_save"),
    path("vacation-planner/period/save/", view.vacation_period_save, name="vacation_period_save"),
    path("vacation-planner/period/delete/", view.vacation_period_delete, name="vacation_period_delete"),
    path("vacation-planner/preview/", view.vacation_preview, name="vacation_preview"),
    path("vacation-planner/holiday/save/", view.custom_holiday_save, name="custom_holiday_save"),
    path("vacation-planner/holiday/delete/", view.custom_holiday_delete, name="custom_holiday_delete"),
    path(
        "vacation-planner/official-holiday/save/",
        view.official_holiday_override_save,
        name="official_holiday_override_save",
    ),
    path(
        "vacation-planner/official-holiday/reset/",
        view.official_holiday_override_reset,
        name="official_holiday_override_reset",
    ),
    path("notifications/claim/", view.claim_desktop_notifications, name="notification_claim"),
    path("notifications/", view.notification_center, name="notification_center"),
    path(
        "notifications/mark-all-read/",
        view.notification_mark_all_read,
        name="notification_mark_all_read",
    ),
    path(
        "notifications/<int:notification_id>/open/",
        view.notification_open,
        name="notification_open",
    ),
    path(
        "notifications/<int:notification_id>/toggle-read/",
        view.notification_toggle_read,
        name="notification_toggle_read",
    ),
    path("messages/", view.messages, name="messages"),
    path("messages/live/", view.messages_live_updates, name="messages_live_updates"),
    path(
        "messages/attachments/<uuid:file_id>/<str:disposition>/",
        view.chat_attachment_download,
        name="chat_attachment_download",
    ),
    path("messages/<int:conversation_id>/live/", view.messages_live_updates, name="messages_live_detail_updates"),
    path("messages/<int:conversation_id>/typing/", view.chat_typing_ping, name="messages_typing_ping"),
    path("messages/<int:conversation_id>/", view.messages, name="messages_detail"),
    path("notes/", view.notes, name="notes"),
    path("notes/<int:note_id>/export/pdf/", view.note_pdf_export, name="note_pdf_export"),
    path("notes/<int:note_id>/export/markdown/", view.note_markdown_export, name="note_markdown_export"),
    path("notes/<int:note_id>/", view.notes, name="note_detail"),
    path("notes/api/create/", view.note_create_api, name="note_create_api"),
    path("notes/api/templates/", view.note_template_create_api, name="note_template_create_api"),
    path(
        "notes/api/templates/<int:template_id>/",
        view.note_template_detail_api,
        name="note_template_detail_api",
    ),
    path("notes/api/folders/", view.note_folders_api, name="note_folders_api"),
    path("notes/api/tree/move/", view.note_tree_move_api, name="note_tree_move_api"),
    path("notes/api/bulk-action/", view.note_bulk_action_api, name="note_bulk_action_api"),
    path(
        "notes/api/folders/<int:folder_id>/",
        view.note_folder_detail_api,
        name="note_folder_detail_api",
    ),
    path("notes/api/share-candidates/", view.note_share_candidates_api, name="note_share_candidates_api"),
    path(
        "notes/api/<int:note_id>/mention-candidates/",
        view.note_mention_candidates_api,
        name="note_mention_candidates_api",
    ),
    path(
        "notes/api/<int:note_id>/link-candidates/",
        view.note_link_candidates_api,
        name="note_link_candidates_api",
    ),
    path("notes/api/<int:note_id>/comments/", view.note_comments_api, name="note_comments_api"),
    path(
        "notes/api/<int:note_id>/comments/<uuid:thread_id>/",
        view.note_comment_thread_api,
        name="note_comment_thread_api",
    ),
    path("notes/api/shortcuts/", view.note_shortcuts_api, name="note_shortcuts_api"),
    path("notes/api/<int:note_id>/", view.note_detail_api, name="note_detail_api"),
    path("notes/api/<int:note_id>/actions/", view.note_action_api, name="note_action_api"),
    path(
        "notes/api/<int:note_id>/folder/",
        view.note_folder_assignment_api,
        name="note_folder_assignment_api",
    ),
    path("notes/api/<int:note_id>/shares/", view.note_shares_api, name="note_shares_api"),
    path(
        "notes/api/<int:note_id>/shares/<int:user_id>/",
        view.note_share_delete_api,
        name="note_share_delete_api",
    ),
    path("notes/api/<int:note_id>/attachments/", view.note_attachment_upload_api, name="note_attachment_upload_api"),
    path("notes/api/<int:note_id>/versions/", view.note_versions_api, name="note_versions_api"),
    path(
        "notes/api/<int:note_id>/versions/<int:version_id>/restore/",
        view.note_version_restore_api,
        name="note_version_restore_api",
    ),
    path(
        "notes/attachments/<uuid:file_id>/<str:disposition>/",
        view.note_attachment_download,
        name="note_attachment_download",
    ),
]
