from .administration_views import administration
from .auth_views import (
    LunoraLoginView,
    LunoraPasswordResetCompleteView,
    LunoraPasswordResetConfirmView,
    LunoraPasswordResetDoneView,
    LunoraPasswordResetView,
    register,
)
from .calendar_views import calendar
from .core_views import home, settings
from .message_views import chat_attachment_download, chat_typing_ping, messages, messages_live_updates
from .notification_views import claim_desktop_notifications
from .note_views import (
    note_action_api,
    note_attachment_download,
    note_attachment_upload_api,
    note_comment_thread_api,
    note_comments_api,
    note_create_api,
    note_detail_api,
    note_mention_candidates_api,
    note_pdf_export,
    note_share_candidates_api,
    note_share_delete_api,
    note_shares_api,
    note_shortcuts_api,
    note_version_restore_api,
    note_versions_api,
    notes,
)
from .search_views import global_search
from .vacation_planner_views import (
    custom_holiday_delete,
    custom_holiday_save,
    official_holiday_override_reset,
    official_holiday_override_save,
    vacation_period_delete,
    vacation_period_save,
    vacation_planner,
    vacation_preview,
    vacation_year_save,
)
from .weather_views import weather, weather_map_tile, weather_point, weather_suggestions

__all__ = [
    "calendar",
    "administration",
    "home",
    "messages",
    "messages_live_updates",
    "chat_typing_ping",
    "chat_attachment_download",
    "claim_desktop_notifications",
    "notes",
    "note_create_api",
    "note_detail_api",
    "note_pdf_export",
    "note_action_api",
    "note_shares_api",
    "note_share_delete_api",
    "note_share_candidates_api",
    "note_attachment_upload_api",
    "note_attachment_download",
    "note_mention_candidates_api",
    "note_comments_api",
    "note_comment_thread_api",
    "note_versions_api",
    "note_version_restore_api",
    "note_shortcuts_api",
    "global_search",
    "vacation_planner",
    "vacation_year_save",
    "vacation_period_save",
    "vacation_period_delete",
    "vacation_preview",
    "custom_holiday_save",
    "custom_holiday_delete",
    "official_holiday_override_save",
    "official_holiday_override_reset",
    "LunoraLoginView",
    "LunoraPasswordResetView",
    "LunoraPasswordResetDoneView",
    "LunoraPasswordResetConfirmView",
    "LunoraPasswordResetCompleteView",
    "register",
    "settings",
    "weather",
    "weather_map_tile",
    "weather_point",
    "weather_suggestions",
]
