from .administration_views import administration
from .auth_views import (
    LunoraLoginView,
    LunoraPasswordResetCompleteView,
    LunoraPasswordResetConfirmView,
    LunoraPasswordResetDoneView,
    LunoraPasswordResetView,
    register,
)
from .calendar_views import calendar
from .core_views import dashboard_layout_update, home, settings
from .message_views import chat_attachment_download, chat_typing_ping, messages, messages_live_updates
from .notification_views import (
    claim_desktop_notifications,
    notification_center,
    notification_mark_all_read,
    notification_open,
    notification_toggle_read,
    web_push_test,
    web_push_subscription,
)
from .pwa_views import offline, service_worker
from .note_views import (
    note_action_api,
    note_attachment_download,
    note_attachment_upload_api,
    note_bulk_action_api,
    note_comment_thread_api,
    note_comments_api,
    note_create_api,
    note_detail_api,
    note_folder_assignment_api,
    note_folder_detail_api,
    note_folders_api,
    note_link_candidates_api,
    note_markdown_export,
    note_mention_candidates_api,
    note_pdf_export,
    note_share_candidates_api,
    note_share_delete_api,
    note_shares_api,
    note_shortcuts_api,
    note_template_create_api,
    note_template_detail_api,
    note_tree_move_api,
    note_version_restore_api,
    note_versions_api,
    notes,
)
from .search_views import global_search
from .tasks_views import tasks
from .vacation_planner_views import (
    custom_holiday_delete,
    custom_holiday_save,
    official_holiday_override_reset,
    official_holiday_override_save,
    vacation_period_delete,
    vacation_period_save,
    vacation_planner,
    vacation_preview,
    vacation_year_save,
)
from .weather_views import weather, weather_map_tile, weather_point, weather_suggestions

__all__ = [
    "calendar",
    "administration",
    "home",
    "dashboard_layout_update",
    "messages",
    "messages_live_updates",
    "chat_typing_ping",
    "chat_attachment_download",
    "claim_desktop_notifications",
    "notification_center",
    "notification_mark_all_read",
    "notification_open",
    "notification_toggle_read",
    "web_push_test",
    "web_push_subscription",
    "offline",
    "service_worker",
    "notes",
    "note_create_api",
    "note_detail_api",
    "note_pdf_export",
    "note_markdown_export",
    "note_action_api",
    "note_bulk_action_api",
    "note_folders_api",
    "note_folder_detail_api",
    "note_folder_assignment_api",
    "note_shares_api",
    "note_share_delete_api",
    "note_share_candidates_api",
    "note_attachment_upload_api",
    "note_attachment_download",
    "note_link_candidates_api",
    "note_mention_candidates_api",
    "note_comments_api",
    "note_comment_thread_api",
    "note_versions_api",
    "note_version_restore_api",
    "note_shortcuts_api",
    "note_template_create_api",
    "note_template_detail_api",
    "note_tree_move_api",
    "global_search",
    "tasks",
    "vacation_planner",
    "vacation_year_save",
    "vacation_period_save",
    "vacation_period_delete",
    "vacation_preview",
    "custom_holiday_save",
    "custom_holiday_delete",
    "official_holiday_override_save",
    "official_holiday_override_reset",
    "LunoraLoginView",
    "LunoraPasswordResetView",
    "LunoraPasswordResetDoneView",
    "LunoraPasswordResetConfirmView",
    "LunoraPasswordResetCompleteView",
    "register",
    "settings",
    "weather",
    "weather_map_tile",
    "weather_point",
    "weather_suggestions",
]
